#!/bin/zsh
set -e

families=(lpc122x lpc13xx lpc17xx)

dump () {
  arm-none-eabi-objcopy -O binary -j .text.$1 dbg.o $1.bin
}

compile () {
  cd $dir
  rm -f *.bin(N)
  cflags=(-Os -mthumb -ffunction-sections --std=gnu99)
  if [[ $dir == lpc12* ]]; then
    cflags=(-mcpu=cortex-m0 $cflags)
  else
    cflags=(-mcpu=cortex-m3 $cflags)
  fi
  arm-none-eabi-gcc $cflags -c -o dbg.o dbg.c
  dump map_normal
  dump map_boot
  dump baud_max
  rm -f dbg.o
}

for dir in $families; do (compile); done
